### PR TITLE
Improvements to Rendering Code

### PR DESCRIPTION
**Pull request by CarbonNotes**
Several improvements of the rendering code: Drawing more than 350 bars will no longer go off-screen, bars will scale their width when the window width changes, and bars will scale their height as the window height changes.

There are also one or two small code quality cleanups.

### CODE REVIEW

**Comment by Hopson97** [comment]
Interesting :) Thanks for the explanations too.

**Comment by Hopson97** [comment]
So I guess the BufferedImage is very similar to framebuffer in OpenGL.

That's actually a pretty smart way of scaling to window size, I was wondering how that could be done :+1:

**Comment by CarbonNotes** [comment]
I'd highly recommend reading this article if you haven't: http://www.oracle.com/technetwork/java/painting-140037.html

It does an awesome job at explaining how painting works in Swing and AWT. It had a lot of thought put into keeping resource usage as minimal as possible, but that can lead to some pitfalls for those who are unfamiliar with it.

**Comment by Hopson97** [comment]
Ah thanks you! I will take a look now.

**Pull request merged**
